### ISSUE TITLE
A protential bug in Jenkins hash function

### ISSUE THREAD

**Issue by seanliu96** [kalininalab/rinminer#1]
Hi,

Thanks for releasing such nice toolkit for frequent subgraph mining. I find something that may cause unexpected bugs in the ash function between Line 494 and 534 in rinminer/rinminer.c. 
In Jenkins hash function, the [wikipedia ](https://en.wikipedia.org/wiki/Jenkins_hash_function) says it is 
`
hash += key;
hash += (hash << 10);
hash ^= (hash >> 6);
`
But the code mistakenly uses 
`
hash ^= (hash << 6);
`
From my view, it is easy to drop the digits at the highest position.
Because there are six numbers and we need to shift (10 + 6) * 6 = 96 times, which is larger than 32 bits of one integer.

I believe it is a bug but I do not know whether it causes something unforeseeing.

Best regards,
Sean

**Comment by sbstnk** [comment]
Hi Sean,

Thanks for the bug report. There indeed was a typo in the hash function. Due to how hash values are used, this could have caused a small performance impact since it makes hash collisions a bit more likely, but it would not have affected the correctness of the results. I've pushed a fix for this now.

Best regards,
Sebastian
